services:
  next:
    build:
      context: ./next
      dockerfile: Dockerfile
    container_name: next_container
    restart: always
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - web

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    restart: always
    depends_on:
      - next
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/cain-dev.es:/etc/ssl/cain-dev.es:ro
    networks:
      - web

networks:
  web:
    driver: bridge